sjtu_minimax_m25:
  label: "MiniMax-M2.7 SJTU"
  base_url: "https://models.sjtu.edu.cn/api/v1"
  api_key: "${SJTU_MODELS_API_KEY}"
  model: "minimax"
  vendor_params: {}
  capabilities:
    vision: false
    function_calling: true
    parallel_tool_calls: true
    reasoning_content: false
    thinking_tag_inline: false
    context_window: 196608

sjtu_glm5:
  label: "GLM-5.1 SJTU"
  base_url: "https://models.sjtu.edu.cn/api/v1"
  api_key: "${SJTU_MODELS_API_KEY}"
  model: "glm"
  vendor_params: {}
  capabilities:
    vision: false
    function_calling: true
    parallel_tool_calls: true
    reasoning_content: false
    thinking_tag_inline: false
    context_window: 131072
sjtu_qwen3vl:
  label: "Qwen3.5-27B SJTU"
  base_url: "https://models.sjtu.edu.cn/api/v1"
  api_key: "${SJTU_MODELS_API_KEY}"
  model: "qwen"
  vendor_params: {}
  capabilities:
    vision: true
    function_calling: false
    parallel_tool_calls: true
    reasoning_content: false
    thinking_tag_inline: false
    context_window: 262144
